-- MySQL Script generated by MySQL Workbench
-- 05/22/16 19:27:54
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Books` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Author` VARCHAR(255) NOT NULL,
  `Title` VARCHAR(255) NOT NULL,
  `Price` BIGINT(20) NOT NULL,
  `Publisher` VARCHAR(100) NOT NULL,
  `Owner` VARCHAR(255) NOT NULL,
  `Description` LONGTEXT NOT NULL,
  `State` INT(11) NOT NULL,
  `Rating` FLOAT NOT NULL,
  `Trade` TINYINT(1) NOT NULL,
  `Language` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `ID` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(200) NOT NULL,
  `Surname` VARCHAR(200) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Password` VARCHAR(45) NOT NULL,
  `Rating` FLOAT NOT NULL,
  `Status` INT NOT NULL,
  `Country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users_has_Books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users_has_Books` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users_has_Books` (
  `Users_ID` INT NOT NULL,
  `Books_ID` INT NOT NULL,
  PRIMARY KEY (`Users_ID`, `Books_ID`),
  INDEX `fk_Users_has_Books_Books1_idx` (`Books_ID` ASC),
  INDEX `fk_Users_has_Books_Users_idx` (`Users_ID` ASC),
  CONSTRAINT `fk_Users_has_Books_Users`
    FOREIGN KEY (`Users_ID`)
    REFERENCES `mydb`.`Users` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_has_Books_Books1`
    FOREIGN KEY (`Books_ID`)
    REFERENCES `mydb`.`Books` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
